services:
  discord-bot:
    build: .
    container_name: thetribe-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    network_mode: "host"