services:
  discord-bot:
    build: .
    container_name: thetribe-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "15015:15015"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true